import json
import os

class ChristianHarp():
    def __init__(self) -> None:
        self.__christian_harp: list[dict[str, list[str]]] = []
    
    def __print_hymns_table(self, hymns: list[dict]) -> None:
        LINE_BREAK: str = "+" + "-" * 50 + "+"
        
        print(LINE_BREAK)
        print(f"| {"Nº":^5} | {"Canção":<40} |")
        print(LINE_BREAK)

        for hymn in hymns:
            number: int = int(hymn["number"])
            title: str = str(hymn["title"])
            
            if len(title) > 40:
                title = title[:40 - 3] + "..."

            print(f"| {number:^5} | {title:<40} |")
        
        print(LINE_BREAK)
    
    def create_hymns_json(self) -> None:
        try:
            HYMNS: list[tuple[str]] = [
                ("Chuvas de Graça"),
                ("Saudosa Lembrança"),
                ("Plena Paz"),
                ("Deus Velará Por Ti"),
                ("Ó Desce Fogo Santo"),
                ("Na Maldição Da Cruz"),
                ("Cristo Cura Sim!"),
                ("Cristo, O Fiel Amigo"),
                ("Marchai Soldados De Cristo"),
                ("Eu Te Louvo"),
                ("Ó Cristão, Eia Avante"),
                ("Vem Já, Pecador"),
                ("Jesus Comprou-me"),
                ("Gozo Em Jesus"),
                ("Conversão" ),
                ("Despertar Para o Trabalho"),
                ("Pensando Em Jesus"),
                ("Grata Nova"),
                ("O Convite De Cristo"),
                ("Olhai o Cordeiro De Deus"),
                ("Gloriosa Aurora"),
                ("Ceia Do Senhor"),
                ("Glória a Jesus"),
                ("Poder Pentecostal"),
                ("Jesus Tu és Bom"),
                ("A Formosa Jerusalém"),
                ("Amor Que Vence"),
                ("Deus Vai Te Guiar"),
                ("O Precioso Sangue"),
                ("Não Sou Meu"),
                ("Glória ao Meu Jesus"),
                ("Meu Cristo! Meu Cristo!"),
                ("Com Tua Mão Segura"),
                ("Milícia De Jesus"),
                ("O Grande Amor"),
                ("O Exilado"),
                ("Cristo Pra Mim"),
                ("O Senhor é Rei"),
                ("Alvo Mais Que a Neve"),
                ("A Cidade Do Bom Jesus"),
                ("A Cristo Coroai"),
                ("Saudai Jesus"),
                ("Doce Lar"),
                ("Oh! Que Glória!"),
                ("Redentor Onipotente"),
                ("Um Pendão Real"),
                ("Rocha Eterna"),
                ("O Dia do Triunfo"),
                ("Aleluia! Já Creio"),
                ("Sempre Fiéis"),
                ("Adoração Reconhecida"),
                ("Tudo Está Bem"),
                ("A Esperança da Igreja"),
                ("Louvemos ao Redentor"),
                ("Mais Perto da Tua Cruz"),
                ("Tudo em Cristo"),
                ("Vivifica- nos Senhor"),
                ("Não Temas"),
                ("Eu creio, Sim"),
                ("Exultação do Crente"),
                ("Deus Tomará Conta de Ti"),
                ("Achei Jesus"),
                ("Acordai, Acordai"),
                ("De Todo o Mundo: Aleluia!"),
                ("Quem Irá?"),
                ("Pronto a Salvar"),
                ("Quem Quer ir Com Cristo?"),
                ("Gozo de Ter Salvação"),
                ("Jesus Quebrou os Meus Grilhões"),
                ("Cristo Vai Voltar"),
                ("Santo és Tu, Senhor"),
                ("Rasgou- se o Véu"),
                ("Vem, Vem a Mim"),
                ("Cristo Virá"),
                ("Em Jesus Tens a Palma da Vitória"),
                ("Vem, ó Pródigo"),
                ("Guarda o Contacto"),
                ("Meu Forte Redentor"),
                ("Sua Graça Me Basta"),
                ("Cristo Te Chama"),
                ("Pode Salvar"),
                ("Um Meigo Salvador"),
                ("Não Posso Explicar"),
                ("O Grande “Eu sou”"),
                ("Deixai Entrar o Espírito de Deus"),
                ("Satisfeito com Cristo"),
                ("Meu Testemunho"),
                ("Revela a Nós Senhor"),
                ("Sublime e Grande Amor"),
                ("Há Paz e Alegria"),
                ("Nívea Luz"),
                ("O Bondoso Salvador"),
                ("Há Trabalho Pronto"),
                ("Na Jerusalém de Deus"),
                ("Ouve, ó Pecador"),
                ("Deixa Penetrar a Luz"),
                ("Há um Caminho Santo"),
                ("Estarás Vigiando?"),
                ("Eis o Dia a Declinar"),
                ("O Bom Consolador"),
                ("A Unção Real"),
                ("Crê na Promessa"),
                ("Caminhemos na Luz"),
                ("Jesus Procura a Ovelha"),
                ("A Gloriosa Esperança"),
                ("Viva Cristo"),
                ("Firme nas Promessas"),
                ("Pelejar Por Jesus"),
                ("Venha a Jesus"),
                ("Clama: Jesus, Jesus!"),
                ("Que Mudança!"),
                ("O Nome Soberano"),
                ("O Celeste Diretor"),
                ("Aceita o Perdão de Jesus"),
                ("Trabalhai e Orai"),
                ("Livre Estou"),
                ("O Senhor Salva a Todo o Pecador"),
                ("Face a Face"),
                ("Inesgotável é Seu Amor"),
                ("Noite de Paz"),
                ("Maravilhoso é Jesus"),
                ("Fogo Divino"),
                ("Cristo Voltará"),
                ("Adoração"),
                ("Quem Dera Hoje Vir!"),
                ("Bem-Aventurança do Crente"),
                ("O Senhor da Ceifa Chama"),
                ("Entrega o Teu Coração"),
                ("A Fonte Salvadora"),
                ("Cristo é Meu!"),
                ("De Valor Em Valor"),
                ("Obreiros do Senhor"),
                ("No Rol do livro"),
                ("Jesus à Porta do Coração"),
                ("O Nome Precioso"),
                ("Jesus, Nosso Socorro"),
                ("Liberto da Escravidão"),
                ("Quem Bate é Jesus Cristo"),
                ("Jesus, Meu Eterno Redentor"),
                ("A Segurança do Crente"),
                ("Guia-me Sempre, Meu Senhor"),
                ("A Cidade Celeste"),
                ("O Verdadeiro Amigo"),
                ("Vem à Assembléia de Deus"),
                ("União do Crente Com Seu Senhor"),
                ("Caminho brilhante"),
                ("Servir a Jesus"),
                ("Bendirei a Jesus"),
                ("Canto do Pescador"),
                ("Para Casamentos"),
                ("Fala Jesus Querido"),
                ("Pela Cruz ao Céu Irei"),
                ("Soldados de Cristo"),
                ("Doce Nome de Jesus"),
                ("Imploramos Teu Poder"),
                ("A Ovelha Perdida"),
                ("Cristo, em Breve, Vem!"),
                ("Que Farás de Jesus Cristo?"),
                ("Cantai, ó Peregrinos"),
                ("Deus Nos Quis Salvar"),
                ("Navegando Pra Terra Celeste"),
                ("O Estandarte da Verdade"),
                ("Cristo Morreu Por Mim"),
                ("Paz Luz e Amor"),
                ("A Armadura Cristã"),
                ("Deixa Entrar o Rei da Glória"),
                ("As Testemunhas de Jesus"),
                ("Meus Irmãos, Nos Jubilemos"),
                ("Oh! Jesus Me Ama"),
                ("Ao Calvário de Horror"),
                ("Um Pecador Remido"),
                ("Ó Vem Te Entregar"),
                ("Os Santos Louvam Ao Senhor"),
                ("Glória, Aleluia, Gloria"),
                ("Irmãos Amados"),
                ("Sacerdotes do Senhor"),
                ("Salvo Estou"),
                ("Gloriosa Paz"),
                ("Redentor Formoso"),
                ("Em Cristo Fruímos a Paz"),
                ("Vem, Celeste Redentor"),
                ("Jesus no Getsêmane"),
                ("Ressuscitou!"),
                ("Meu Jesus! Meu Jesus!"),
                ("Invocação e Louvor"),
                ("De Valor em Valor"),
                ("Mais Perto Meu Deus de Ti!"),
                ("O Gozo do Céu"),
                ("Glória ao Salvador"),
                ("Cristo! Meu Cristo!"),
                ("O Meu Jesus"),
                ("Pelo Sangue"),
                ("A Alma Abatida"),
                ("Jesus Me Guiará"),
                ("Benigno Salvador"),
                ("Uma Flor Gloriosa"),
                ("O Lar da Glória"),
                ("Jesus o Bom Amigo"),
                ("A Ceia do Senhor"),
                ("O Bondoso Amigo"),
                ("A Decisão"),
                ("Lugar de Delícias"),
                ("Deixai as Ilusões"),
                ("O Peregrino da Terra"),
                ("Graça, Graça"),
                ("O Clarim nos Alerta"),
                ("Jerusalém Divina"),
                ("Vem a Cristo"),
                ("A Voz do Bom Pastor"),
                ("Fala, fala, Senhor"),
                ("Vem a Deus"),
                ("Os Guerreiros Se Preparam"),
                ("Sobre a Terra Vou Andando"),
                ("Desejamos ir Lá"),
                ("Ver-nos-emos"),
                ("Louvai a Deus"),
                ("Ouve Sua Voz"),
                ("Dá Teu Fardo a Jesus"),
                ("O Amor do Criador"),
                ("Ide Segar"),
                ("Opera em Mim"),
                ("Vem a Jesus, ó Perdido"),
                ("Na Minh’Alma Reina a Paz"),
                ("É o Tempo de Segar"),
                ("Sê Valente"),
                ("Cristo, Teu Santo Amor"),
                ("Deus Amou de Tal Maneira"),
                ("Este Mundo Não Compreende"),
                ("Jesus, ó Meigo Salvador"),
                ("Nós Vogamos Nesta Nau"),
                ("Não Foi Com Ouro"),
                ("Os Bem Aventurados"),
                ("A Ceia Do Senhor"),
                ("O Gozo Dos Santos"),
                ("Já Sei, Já Sei"),
                ("Já Nos Lavou"),
                ("O Gozo de Estar Preparado"),
                ("Ó Pecador Desalentado"),
                ("Imploramos o Consolador"),
                ("Oh Dia Alegre"),
                ("Marchemos Sem Temor"),
                ("Eu Confio Firmemente"),
                ("Ao Abrir o Culto"),
                ("Louvai a Jesus"),
                ("Paz de Deus em Jesus Encontrei"),
                ("O Descanso em Jesus"),
                ("Deus Nos Guarde No Seu Amor"),
                ("Hosana e Glória"),
                ("Ó vem, Senhor, e Habita"),
                ("Noiva de Jesus, Apronta-te"),
                ("Ao Culto Não Faltar"),
                ("Santo, Santo és Tu Senhor"),
                ("Avante, ó Crentes"),
                ("Mais Perto de Jesus"),
                ("Meu Redentor"),
                ("Abandona Este Mundo de Horror"),
                ("O Perdão Sem Igual"),
                ("Na Rocha Eterna Firmado"),
                ("Creio eu na Bíblia"),
                ("Avante com o Nosso Capitão"),
                ("Alma Triste, Abatida"),
                ("Senhor, Estás Comigo"),
                ("Ao Fim do Culto"),
                ("Ó Pai Celeste"),
                ("Doce é Crer em Cristo"),
                ("Resgatados Fomos"),
                ("Jesus Minha Força"),
                ("Confiante em Deus"),
                ("Louvarei ao Meu Amado"),
                ("Louvando ao Nosso Salvador"),
                ("Na Mansão do Salvador"),
                ("Quando Jesus Aparecer"),
                ("Só a Ti Recorrerei"),
                ("Jesus é a Luz do Mundo"),
                ("Ó Acorda, Desperta!"),
                ("Em Canaã Eu Entrarei"),
                ("Salvo Estás? Limpo Estás?"),
                ("Levar a Cruz"),
                ("Ali Quero ir, e Tu?"),
                ("Ó Jesus, Te Suplico"),
                ("Vem Sem Tardar"),
                ("Que Sangue Precioso"),
                ("O Pastor e as Ovelhas"),
                ("Bendito Cristo, Eis-me Aqui"),
                ("Tu És o Meu Gozo"),
                ("Não Tarda Vir Jesus!"),
                ("Oh, Foi o Sangue"),
                ("A Palavra da Cruz"),
                ("Sob o Sangue Teu"),
                ("Teu Espírito Vem Derramar"),
                ("A Mensagem da Cruz"),
                ("Qual o Preço do Perdão"),
                ("Jesus no Calvário"),
                ("Eu Vou Com Jesus"),
                ("Novo Canto de Louvor"),
                ("No Jardim"),
                ("Abundância de Cristo"),
                ("Avante, Servos de Jesus"),
                ("Há um Canto Novo"),
                ("Nossa Esperança"),
                ("Vem Cear"),
                ("Não Murmures; Canta"),
                ("Precisamos de Jesus"),
                ("A Face Adorada de Jesus"),
                ("Campeões da luz"),
                ("A Palavra de Deus é um Tesouro"),
                ("Louvor ao Deus Trino"),
                ("Só o Sangue de Jesus"),
                ("Ao Findar do Dia"),
                ("Avante Eu Vou"),
                ("Jesus, Meu Salvador"),
                ("A Vinda de Cristo"),
                ("Louvor a Trindade"),
                ("O pai bondoso"),
                ("Oh! Amor Bendito"),
                ("Em Busca de Sião"),
                ("Jesus Vem Triunfante"),
                ("Ao Lar Paternal"),
                ("Ainda Há Lugar"),
                ("Seguir a Cristo"),
                ("Só em Jesus"),
                ("As Santas Escrituras"),
                ("Levantai Vossos Olhos"),
                ("Jesus, o Melhor Amigo"),
                ("A Luz do Céu Raiou"),
                ("Oh! Meu Jesus"),
                ("Teu Nome Precioso"),
                ("O Pão da Vida"),
                ("Jesus é Minha Paz"),
                ("A Fé dos Santos"),
                ("Ó Caro Salvador"),
                ("Para o Céu eu vou"),
                ("O Céu, Meu Lar"),
                ("O Fim Vem, Cuidado!"),
                ("Mui Perto Está o Dia"),
                ("Oração de Elias"),
                ("O Bom Jesus"),
                ("Quero Jesus, Tua Luz"),
                ("Jesus Ressuscitado"),
                ("Um Povo Forte"),
                ("A Aspiração da Alma"),
                ("As Cordas do Coração"),
                ("Abre o Coração"),
                ("Um Amigo Entre os Lírios"),
                ("Oh! Tenho Gozo"),
                ("É Meu o Céu"),
                ("Vem a Cristo"),
                ("Longe de Jesus"),
                ("Os Dons do Céu"),
                ("A História da Cruz"),
                ("A Felicidade da Salvação"),
                ("Jesus, Nossa Esperança"),
                ("Vem, ó Pródigo"),
                ("O Cuidado da Alma"),
                ("Fala do Amor de Cristo"),
                ("Oração Dominical"),
                ("O Fim das Lutas"),
                ("Senhor, Manda Teu Poder"),
                ("Vem a Mim, Pecador"),
                ("A Preciosa Fonte"),
                ("O Peregrino da Glória"),
                ("O Espírito Diz: Vem!"),
                ("Consagração"),
                ("Oh, que Paz!"),
                ("Confiança em Jesus"),
                ("O Nascimento de Jesus"),
                ("Espírito Consolador"),
                ("Jesus, Tudo prá Mim"),
                ("Sob as Asas de Deus"),
                ("Grato a Ti"),
                ("Breve Vem o Dia"),
                ("Vencerá"),
                ("Vem a Teu Salvador"),
                ("Vida Abundante"),
                ("A Igreja Universal"),
                ("Vamos Todos Trabalhar"),
                ("As Promessas Que Não Falham"),
                ("As Pisadas do Mestre"),
                ("Salvo de Graça"),
                ("Abraão e Seu Sacrifício"),
                ("O Cordeiro de Deus"),
                ("Olhando Para o Calvário"),
                ("O Sustento da Alma"),
                ("Sinto Vida do Senhor"),
                ("Amemos o Senhor"),
                ("Vencidos os Combates"),
                ("Derrama Teu Espírito"),
                ("Canta, ó Crente"),
                ("Lava-me ó Deus"),
                ("Um Coração Bondoso"),
                ("Jesus no Monte da Ascensão"),
                ("Peregrinos Somos"),
                ("Há um Amigo Mui Chegado"),
                ("A Mão ao Arado!"),
                ("Ide por Todo Mundo"),
                ("Além do Nosso Entendimento"),
                ("O Salvador me Achou"),
                ("Perto do Meu Redentor"),
                ("Terra de Jesus"),
                ("Em Jesus"),
                ("Jesus Voltará"),
                ("Ao Gólgota"),
                ("Gozo Real"),
                ("Em Glória Virá"),
                ("Queres Perdão"),
                ("A Sombra do Meu Redentor"),
                ("Ó Criador Bendito"),
                ("Abre os Meus Olhos"),
                ("Trabalhadores do Evangelho"),
                ("Jesus Meu Rei Glorioso"),
                ("Nós Somos Teus"),
                ("Jesus Cristo, Bem Amado"),
                ("Meu Pastor"),
                ("Tem Compaixão do Pecador"),
                ("Jesus Te Quer Curar"),
                ("Quando o Povo Salvo Entrar"),
                ("Bastante Para Mim"),
                ("Sou Um Soldado"),
                ("Vinde, Pecadores"),
                ("O Que Buscas Ansioso?"),
                ("Careço de Jesus"),
                ("No Céu não Entra Pecado"),
                ("De Ti Preciso Mais"),
                ("Seu Precioso Sangue"),
                ("Perdido Andei"),
                ("União Dos Irmãos"),
                ("Vai Orando"),
                ("A estrela da Alva"),
                ("Escuta o Evangelho"),
                ("Evangelho da Salvação"),
                ("Cristo Chama o Pecador"),
                ("Consagrado ao Senhor"),
                ("Sois Benvindos"),
                ("A Teus Pés"),
                ("Jesus Me Levantou"),
                ("Crentes Cantai!"),
                ("O Dom Celeste"),
                ("Voltai-vos Para Mim"),
                ("Aos Pés de Cristo Prostrados"),
                ("Faze Já o seu Querer"),
                ("A Chuva do Consolador"),
                ("Breve Verei o Bom Jesus"),
                ("Larga o Mundo!"),
                ("Escuta, Pobre Pecador"),
                ("Resgatado Com O Sangue de Cristo"),
                ("Ó Vem Já!"),
                ("Nascer de Novo"),
                ("Crentes, Avançai"),
                ("À Beira da Estrada"),
                ("Sol da Justiça"),
                ("Meu Jesus Vem"),
                ("Seguirei a Cristo"),
                ("Deus é o mesmo"),
                ("Alegrai-vos, ó Remidos"),
                ("O Povo de Deus na Terra"),
                ("A Fonte Transbordante"),
                ("O Festim de Glória"),
                ("Guia Meus Passos"),
                ("As Firmes Promessas"),
                ("Dize-o a Cristo"),
                ("Jesus Chorou Sobre Jerusalém"),
                ("Glória ao Salvador"),
                ("O Povo de Abraão"),
                ("Plena Graça"),
                ("Ele Sofreu Por mim"),
                ("Que Maravilha"),
                ("Sobre as Ondas do Mar"),
                ("Cristo Está Chamando"),
                ("Ao Estrugir a Trombeta"),
                ("Batismo"),
                ("Avançai Fiéis"),
                ("Em Meu Lugar"),
                ("Outro Bem Não Acharei"),
                ("Paz, Doce Paz"),
                ("Em Belém"),
                ("O Cego de Jericó"),
                ("Sede Fortes"),
                ("Eis-me Jesus"),
                ("Ao Raiar do Novo Ano"),
                ("Fim do Ano"),
                ("Cristo e Sua Humilhação"),
                ("Comunhão"),
                ("Ora Vem Jesus"),
                ("Meus Pecados Levou"),
                ("Andando Para o Céu"),
                ("Vasos Transbordantes"),
                ("Doxologia"),
                ("O Áureo Dia"),
                ("Chegai Para Adorar"),
                ("Passando Está"),
                ("Há Poder no Sangue de Jesus"),
                ("Jesus Virá do Céu"),
                ("Ao Pai Voltai"),
                ("Jerusalém Celestial"),
                ("Cristo à Porta Está"),
                ("Jesus me Tirou da Lama"),
                ("Meu Bom Salvador"),
                ("Guia-me ó Salvador"),
                ("A Santa Bíblia"),
                ("Quero ver a Jesus Cristo"),
                ("Vencendo Com o Bom Capitão"),
                ("Ó Pastor Bendito"),
                ("Vidas Consagradas ao Trabalho"),
                ("Momento Solene"),
                ("As Palavras de Jesus"),
                ("Bíblia Sagrada"),
                ("Jesus Salva"),
                ("Sua Palavra Revelada"),
                ("Ao Passar o Jordão"),
                ("A Riqueza Divinal"),
                ("Glorioso Deus"),
                ("O Amor Inesgotável"),
                ("Minha Alma Quer Ter"),
                ("Em Glória Esplendente"),
                ("Se Cristo Comigo Vai"),
                ("Cristo Meu Vero Amigo"),
                ("Cura Divina"),
                ("Salva-Vidas"),
                ("Achei Jesus, Meu Salvador"),
                ("A Doce e Preciosa Voz"),
                ("Vem o Passo Dar!"),
                ("Rei da Glória"),
                ("Cristo, a Fonte Escondida"),
                ("Cristo Pensa em Mim"),
                ("Vencendo Vem Jesus"),
                ("Grandioso És Tu"),
                ("Dominador É Deus"),
                ("Eu Te Amo, Ó Deus"),
                ("Em Sua Graça"),
                ("Vivifica a Tua Igreja"),
                ("Nome Precioso"),
                ("Santo Nome"),
                ("Honras Sejam ao Cordeiro"),
                ("Cristo É Real Pra Mim"),
                ("Tu És Fiel, Senhor"),
                ("Amigo Sem Igual"),
                ("Sempre Comigo"),
                ("Tu, Senhor, És Nosso Amigo"),
                ("Ao Pensar na Dor Crucial"),
                ("Ao Ver a Cruz"),
                ("Calvário, Revelação de Amor"),
                ("História de Cristo"),
                ("Cristo, Meu redentor"),
                ("Creio, Senhor"),
                ("Porque Ele Vive"),
                ("Manhã da Ressurreição"),
                ("O Rei Está Voltando"),
                ("Breve Jesus Há de Vir"),
                ("Ora Vem, Senhor Jesus"),
                ("Breve Ele Volta"),
                ("O Santo Espírito"),
                ("Quando para o Céu Nós Formos"),
                ("Oh! Pai, o Santo Espírito"),
                ("O Evangelho"),
                ("O Redentor"),
                ("Lê a Bíblia"),
                ("A Palavra da Vida"),
                ("Daí-me a Bíblia"),
                ("Bíblia Sagrada"),
                ("Tenho Paz em Meu Ser"),
                ("Que Bênção!"),
                ("Autor da Vida"),
                ("Sempre Feliz"),
                ("Conta as Bênçãos"),
                ("Tu És Meu"),
                ("Paz Perfeita, Sim, Busquei"),
                ("Sou Feliz"),
                ("Manso e Suave"),
                ("Morri na cruz por Ti"),
                ("A Última Hora"),
                ("Rende o Coração"),
                ("A Porta Sou"),
                ("A Graça de Nosso Senhor"),
                ("Ó Pai Bondoso"),
                ("Espero em Ti"),
                ("Assim como estou"),
                ("Em Fervente Oração"),
                ("Sossegai!"),
                ("Porque te Afliges?"),
                ("Salmo 121"),
                ("Castelo Forte"),
                ("A Barca da Vida"),
                ("Sê Tu Meu Guia"),
                ("O Piloto"),
                ("Jesus me Satisfaz"),
                ("Gozo e Vida Tenho"),
                ("Neste Lenho me Glorio"),
                ("Sou Mui Feliz"),
                ("Quádruplo Amém"),
                ("Contentamento"),
                ("Pura, Sim, Mais Pura"),
                ("O Lugar de Bênção e Paz"),
                ("Estou Seguro"),
                ("Fé Persistente"),
                ("Somente a Ti!"),
                ("Gratidão"),
                ("Graça Dou"),
                ("Riquezas do Céu"),
                ("Herdeiro do Reino"),
                ("Mãos ao Trabalho"),
                ("A Seara está Madura"),
                ("Juntos Trabalhamos"),
                ("Método de Deus"),
                ("Senhor, os Mensageiros Teus"),
                ("Quero te Servir"),
                ("Triunfo"),
                ("Luz após Trevas"),
                ("Se em Teu Caminho"),
                ("Vitória Deus Dará a Mim"),
                ("Fé É a Vitória"),
                ("Cristo, Comandante"),
                ("Ó Pai Eterno"),
                ("Vitória Final"),
                ("Terra Feliz"),
                ("Vou Rumo ao Meu Lar"),
                ("Quanto Almejo!"),
                ("Quanto Anelo"),
                ("É Nosso o Lar"),
                ("Meu Lar, Jerusalém"),
                ("Na Jornada Para Jerusalém"),
                ("Juntos, no Céu"),
                ("Tão Grato me é Lembrar"),
                ("Oh, Sim, Bem Sei"),
                ("Anseio um Lugar de Amor"),
                ("Glória Indizível"),
                ("Tríplice Amém"),
                ("Finda-se Minha Prisão"),
                ("Além do céu Azul"),
                ("Conversaremos Ali no Céu"),
                ("Não Há Separação na Glória"),
                ("Neste Lugar"),
                ("Mais um Templo"),
                ("Meu Brasil"),
                ("Oração pela Pátria"),
                ("Eis o Brasil em Tuas Mãos"),
                ("Por nossa Pátria Oramos"),
                ("Hino à Bandeira Nacional"),
                ("Hino Nacional Brasileiro"),
                ("Hino da Independência"),
                ("Hino da Proclamação da República do Brasil")
            ]
            
            for index, title in enumerate(HYMNS, start=1):
                self.__christian_harp.extend([{
                    "number": index,
                    "title": title,
                    "letter": [],
                    "chorus": None
                }])
            
            FILE_NAME: str = "christian_harp.json"

            if os.path.exists(FILE_NAME):
                if input(f"O arquivo \"{FILE_NAME}\" já existe. Deseja sobrescrevê-lo? (S/n):\n> ").strip().lower() != "s":
                    print("Operação cancelada.")
                    return

            with open(FILE_NAME, "w", encoding = "utf-8") as json_file:
                json.dump(self.__christian_harp, json_file, ensure_ascii = False, indent = 4)

            print(f"Arquivo \"{FILE_NAME}\" com {len(self.__christian_harp)} hinos foi gerado com sucesso em: [{os.path.abspath(FILE_NAME)}]\n")
        
            self.__print_hymns_table(self.__christian_harp)
        
        except Exception as error:
            print(f"[{type(error).__name__}] Não foi possível gerar o JSON: {error}")

            raise error
